#!/bin/sh
set -e

DIR="/usr/src/nell/openssl"

case "$1" in
    configure)
        cd ${DIR} && debuild -us -uc -b
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
