set -e
LIMESURVEY_DB_USERNAME=${LIMESURVEY_DB_USERNAME:-limesurvey}
LIMESURVEY_DB_PASSWORD=${LIMESURVEY_DB_PASSWORD:-password}
LIMESURVEY_DB_HOST=${LIMESURVEY_DB_HOST:-10.1.0.1}
LIMESURVEY_DB_PORT=${LIMESURVEY_DB_PORT:-5432}
LIMESURVEY_DB_NAME=${LIMESURVEY_DB_NAME:-limesurvey}

LIMESURVEY_TEMPLATE='/var/lib/limesurvey/config.php'
LIMESURVEY_CONFIGFILE='/var/www/limesurvey/application/config/config.php'

cat "${LIMESURVEY_TEMPLATE}" | sed -s  's/LIMESURVEY_DB_USERNAME/'"${LIMESURVEY_DB_USERNAME}"'/g' "${LIMESURVEY_CONFIGFILE}" > ${LIMESURVEY_CONFIGFILE}
cat "${LIMESURVEY_TEMPLATE}" | sed -s  's/LIMESURVEY_DB_PASSWORD/'"${LIMESURVEY_DB_PASSWORD}"'/g' "${LIMESURVEY_CONFIGFILE}" > ${LIMESURVEY_CONFIGFILE}
cat "${LIMESURVEY_TEMPLATE}" | sed -s  's/LIMESURVEY_DB_HOST/'"${LIMESURVEY_DB_HOST}"'/g' "${LIMESURVEY_CONFIGFILE}" > ${LIMESURVEY_CONFIGFILE}
cat "${LIMESURVEY_TEMPLATE}" | sed -s  's/LIMESURVEY_DB_PORT/'"${LIMESURVEY_DB_PORT}"'/g' "${LIMESURVEY_CONFIGFILE}" > ${LIMESURVEY_CONFIGFILE}
cat "${LIMESURVEY_TEMPLATE}" | sed -s  's/LIMESURVEY_DB_NAME/'"${LIMESURVEY_DB_NAME}"'/g' "${LIMESURVEY_CONFIGFILE}" > ${LIMESURVEY_CONFIGFILE}
